title: "Next.js + AWS AppSync + AWS CDKで作るTodoアプリ"
summary: "Next.js, AWS AppSync, AWS CDKを使ってTodoアプリを作ってみたのでご紹介します。"
topics: ["nextjs", "graphql", "appsync", "awscdk"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
